# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kijiji',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
